Add ZFS support to vzmigrate.in

diff --git a/bin/vzmigrate.in b/bin/vzmigrate.in
--- a/bin/vzmigrate.in
+++ b/bin/vzmigrate.in
@@ -49,6 +49,9 @@ vzconf="@PKGCONFDIR@/vz.conf"
 tmpdir="/var/tmp"
 act_scripts=
 PLOOP=no
+ZFS=no
+ZFSFULL=no
+ZFS_ROOT=vz/private
 RSYNC1_OPTIONS=
 PLOOP_DEV=
 TOP_DELTA=
@@ -75,6 +78,7 @@ MIG_ERR_UNSUP_CPT_VER=17
 MIG_ERR_UNSUP_CPU=18
 MIG_ERR_CANT_READ_REMOTE_CONFIG=19
 MIG_ERR_LOCKED=20
+MIG_ERR_ZFS=99
 
 # For local vzctl to work, make sure @SBINDIR@ is in $PATH
 if ! echo ":${PATH}:" | fgrep -q ':@SBINDIR@:'; then
@@ -128,6 +132,8 @@ Options:
 -t, --times
 	At the end of live migration, output various timings for migration
 	stages that affect total suspended CT time.
+-z, --zfs
+	Use zfs snapsohts for migration
 
 Examples:
 	Online migration of CT #101 to foo.com:
@@ -526,10 +532,11 @@ parse_nodeps() {
 
 [ $# = 0 ] && usage
 
-OPTS=$(getopt -n 'vzmigrate' -o vr:csf::th \
+OPTS=$(getopt -n 'vzmigrate' -o vr:csf::tzh \
 	--longoptions live,online,remove-area:,keep-dst \
 	--longoptions compact,snapshot,check-only,dry-run \
 	--longoptions nodeps::,ssh:,rsync:,times,ssh-mux,help,usage \
+	--longoptions zfs \
 	-- "$@")
 
 [ $? -eq 0 ] || bad_usage
@@ -589,6 +596,9 @@ while true; do
 		;;
 	-h|--help|--usage)
 		usage
+		;;
+	-z|--zfs)
+		ZFS=yes
 		;;
 	--)
 		shift
@@ -797,6 +807,30 @@ if [ "$PLOOP" = "yes" ]; then
 		undo_lock
 		exit $MIG_ERR_UNSUP_PLOOP
 	fi
+elif [ "$ZFS" = "yes" ]; then
+	log 2 "Checking if zfs root $ZFS_ROOT exists on destination node"
+	if ! logexec 2 $SSH "root@$host" "zfs list -Ht filesystem -o name $ZFS_ROOT >/dev/null" ; then
+		log 0 "zfs not working or zfs root missing on destination node, can't migrate"
+		undo_lock
+		exit $MIG_ERROR_ZFS
+	fi
+	log 2 "Checking if zfs dataset exists on destination node"
+	if ! logexec 2 $SSH "root@$host" "zfs list -Ht filesystem -o name $ZFS_ROOT/$VEID >/dev/null" ; then
+		log 2 "ZFS dataset does not exist on remote node, full transfer"
+		ZFSFULL=yes
+	else
+		ZFS_LASTSNAP=`$SSH "root@$host" "zfs list -d 1 -Ht snapshot -o name $ZFS_ROOT/$VEID" | tail -1 | awk -F@ '{ print $2 }'`
+		if [ -z "$ZFS_LASTSNAP" ]; then
+			log 0 "remote zfs dataset has no snapshots"
+			undo_lock
+			exit $MIG_ERROR_ZFS
+		fi
+		if ! zfs list -d 1 -Ht snapshot $ZFS_ROOT/$VEID@$ZFS_LASTSNAP >/dev/null ; then
+			log 0 "snapshot $ZFS_ROOT/$VEID@$ZFS_LASTSNAP not found on local system"
+			undo_lock
+			exit $MIG_ERROR_ZFS
+		fi
+	fi
 else
 	# non-ploop case: can use sparse rsync, can't do compact/snapshot
 	RSYNC1_OPTIONS="--sparse"
@@ -895,6 +929,49 @@ if ! $SSH "root@$host" "mkdir -p $VE_PRIVATE_REMOTE"; then
 	undo_private
 	exit $MIG_ERR_COPY
 fi
+if [ "$ZFS" = "yes" ]; then
+	log 1 "Syncing ZFS"
+	ZFS_SNAP=migrate_`date +%Y%m%d.%H%M%S`
+	log 2 "Creating zfs snapshot $ZFS_ROOT/$VEID@$ZFS_SNAP"
+	if ! zfs snapshot $ZFS_ROOT/$VEID@$ZFS_SNAP >/dev/null; then
+		log 0 "Failed to create zfs snapshot $ZFS_ROOT/$VEID@$ZFS_SNAP"
+		undo_private
+		exit $MIG_ERR_ZFS
+	fi
+	if [ "$ZFSFULL" = "yes" ]; then
+		log 2 "Sending full zfs dataset to remote host"
+		if ! zfs send -pR $ZFS_ROOT/$VEID@$ZFS_SNAP | $SSH "root@$host" "zfs receive -u $ZFS_ROOT/$VEID >/dev/null"; then
+			log 0 "Failed to send full dataset $ZFS_ROOT/$VEID@$ZFS_SNAP"
+			zfs destroy $ZFS_ROOT/$VEID@$ZFS_SNAP > /dev/null
+			undo_private
+			exit $MIG_ERR_ZFS
+		fi
+	else
+		log 2 "Sending incremental zfs to remote host"
+		MOUNTED=`$SSH "root@$host" "grep -E ^$ZFS_ROOT/$VEID\  /proc/mounts"`
+		if [ -n "$MOUNTED" ]; then
+			if ! logexec 2 $SSH "root@$host" "zfs umount $ZFS_ROOT/$VEID >/dev/null"; then
+				log 0 "Failed to umount $ZFS_ROOT/$VEID on remote node"
+				zfs destroy $ZFS_ROOT/$VEID@$ZFS_SNAP > /dev/null
+				undo_private
+				exit $MIG_ERR_ZFS
+			fi
+		fi
+
+		if ! zfs send -pI @$ZFS_LASTSNAP $ZFS_ROOT/$VEID@$ZFS_SNAP | $SSH "root@$host" "zfs receive -Fu $ZFS_ROOT/$VEID >/dev/null"; then
+			log 0 "Failed to send incremental snapshot $ZFS_ROOT/$VEID@$ZFS_SNAP"
+			zfs destroy $ZFS_ROOT/$VEID@$ZFS_SNAP > /dev/null
+			undo_private
+			exit $MIG_ERR_ZFS
+		fi
+
+		if ! logexec 2 $SSH "root@$host" "zfs mount $ZFS_ROOT/$VEID >/dev/null"; then
+			log 0 "Failed to mount $ZFS_ROOT/$VEID on remote node"
+			undo_private
+			exit $MIG_ERR_ZFS
+		fi
+	fi
+fi
 
 if [ "${DISK_QUOTA}" != "no" ]; then
 	log 1 "Initializing remote quota"
@@ -940,14 +1017,17 @@ if [ "$PLOOP" = "yes" -a "$state" = "running" ]; then
 	RSYNC1_OPTIONS="--exclude $TOP_DELTA"
 fi
 
-log 1 "Syncing private"
-$RSYNC $RSYNC1_OPTIONS "$VE_PRIVATE/" "root@$host:$VE_PRIVATE_REMOTE/"
-RET=$?
-# Ignore rsync error 24 "Partial transfer due to vanished source files"
-if [ $RET != 24 ] && [ $RET != 0 ]; then
-	log 0 "Failed to sync container private areas"
-	undo_quota_on
-	exit $MIG_ERR_COPY
+
+if [ "$ZFS" != "yes" ]; then
+	log 1 "Syncing private"
+	$RSYNC $RSYNC1_OPTIONS "$VE_PRIVATE/" "root@$host:$VE_PRIVATE_REMOTE/"
+	RET=$?
+	# Ignore rsync error 24 "Partial transfer due to vanished source files"
+	if [ $RET != 24 ] && [ $RET != 0 ]; then
+		log 0 "Failed to sync container private areas"
+		undo_quota_on
+		exit $MIG_ERR_COPY
+	fi
 fi
 
 if [ "$PLOOP" = "yes" ]; then
@@ -1051,12 +1131,66 @@ else
 fi
 
 time_rsync2=$(date +%s.%N)
-if [ "$state" = "running" -a "$PLOOP" != "yes" ]; then
+if [ "$state" = "running" -a "$PLOOP" != "yes" -a "$ZFS" != "yes" ]; then
 	log 2 "Syncing private (2nd pass)"
 	if ! $RSYNC "$VE_PRIVATE/" "root@$host:$VE_PRIVATE_REMOTE/"; then
 		log 0 "Failed to sync container private areas"
 		undo_source_stage
 		exit $MIG_ERR_COPY
+	fi
+elif [ "$state" = "running" -a "$PLOOP" != "yes" -a "$ZFS" == "yes" ]; then
+	log 2 "Syncing ZFS snapshot (2nd pass)"
+	if [ "${DISK_QUOTA}" != "no" ]; then
+		if ! logexec 2 $SSH "root@$host" "vzquota off $VEID"; then
+			log 0 "Failed to turn off quota for $VEID"
+			undo_source_stage
+			exit $MIG_ERR_ZFS
+		fi
+	fi
+	ZFS_SNAP2=migrate_`date +%Y%m%d.%H%M%S`
+	log 2 "Creating zfs snapshot $ZFS_ROOT/$VEID@$ZFS_SNAP2"
+	if ! zfs snapshot $ZFS_ROOT/$VEID@$ZFS_SNAP2 >/dev/null; then
+		log 0 "Failed to create zfs snapshot $ZFS_ROOT/$VEID@$ZFS_SNAP2"
+		undo_source_stage
+		exit $MIG_ERR_ZFS
+	fi
+	log 2 "Sending incremental zfs to remote host"
+	MOUNTED=`$SSH "root@$host" "grep -E ^$ZFS_ROOT/$VEID\  /proc/mounts"`
+	if [ -n "$MOUNTED" ]; then
+		if ! logexec 2 $SSH "root@$host" "zfs umount $ZFS_ROOT/$VEID >/dev/null"; then
+			log 0 "Failed to umount $ZFS_ROOT/$VEID on remote node"
+			zfs destroy $ZFS_ROOT/$VEID@$ZFS_SNAP2 > /dev/null
+			undo_source_stage
+			exit $MIG_ERR_ZFS
+		fi
+	fi
+	if ! zfs send -I @$ZFS_SNAP $ZFS_ROOT/$VEID@$ZFS_SNAP2 | $SSH "root@$host" "zfs receive -Fu $ZFS_ROOT/$VEID >/dev/null"; then
+		log 0 "Failed to send incremental snapshot $ZFS_ROOT/$VEID@$ZFS_SNAP2"
+		zfs destroy $ZFS_ROOT/$VEID@$ZFS_SNAP2 > /dev/null
+		undo_source_stage
+		exit $MIG_ERR_ZFS
+	fi
+	if ! logexec 2 $SSH "root@$host" "zfs destroy $ZFS_ROOT/$VEID@$ZFS_SNAP"; then
+		log 0 "Failed to destroy $ZFS_ROOT/$VEID@$ZFS_SNAP on remote node"
+		undo_source_stage
+		exit $MIG_ERR_ZFS
+	fi
+	if ! zfs destroy $ZFS_ROOT/$VEID@$ZFS_SNAP; then
+		log 0 "Failed to destroy $ZFS_ROOT/$VEID@$ZFS_SNAP on local node"
+		undo_source_stage
+		exit $MIG_ERR_ZFS
+	fi
+	if ! logexec 2 $SSH "root@$host" "zfs mount $ZFS_ROOT/$VEID >/dev/null"; then
+		log 0 "Failed to mount $ZFS_ROOT/$VEID on remote node"
+		undo_source_stage
+		exit $MIG_ERR_ZFS
+	fi
+	if [ "${DISK_QUOTA}" != "no" ]; then
+		if ! logexec 2 $SSH "root@$host" "vzquota on $VEID"; then
+			log 0 "Failed to turn on quota for $VEID"
+			undo_source_stage
+			exit $MIG_ERR_ZFS
+		fi
 	fi
 fi
 
